namespace ArchPM.NetCore.Tests.ClassExtensionSampleClassStructure
{
    public class PositionPaymentSOM
    {
        public string TaxGroup { get; set; }

        public decimal CostPrice { get; set; }

        public decimal SalesPrice { get; set; }

        public string CurrencyCode { get; set; }

        public decimal Discount { get; set; }

        public decimal PriceUnit { get; set; }

        public string TaxItemGroup { get; set; }

        public bool TaxAutoGenerated { get; set; }
    }
}